name: verify
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_call:
    secrets:
      CLIENT_STAGING_ID:     {required: true}
      CLIENT_SECRET_STAGING: {required: true}
      API_STAGING_BASE_URL:  {required: true}
      ENVIRONMENT:           {required: true}

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6
      - name: Run linters
        run: |
           bundle exec rubocop

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6

      - name: Run tests
        env:
          CLIENT_ID: ${{secrets.CLIENT_STAGING_ID }}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET_STAGING }}
          API_STAGING_BASE_URL: ${{secrets.API_STAGING_BASE_URL}}
          ENVIRONMENT: ${{secrets.ENVIRONMENT}}
        run: bundle exec rspec
